name: FOSSA

on:
  workflow_dispatch:
  push:
    tags:
      - v*
    branches:
      - v*

jobs:
  fossa:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # needed for the Vault authentication

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Load Secrets from Vault
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/fossa/credentials token | FOSSA

      - name: Check FOSSA compliance
        uses: fossas/fossa-action@main
        with:
          api-key: ${{ env.FOSSA }}
